spring.application.name=weather-app
geocoding.url=http://api.openweathermap.org/geo/1.0/direct
weather.url=https://api.openweathermap.org/data/2.5/weather
#
# in real world systems, sensitive information like api keys must be securely managed, UNLIKE this example below
#
api.key=